
metricbeat.config.modules:
  enabled: false

metricbeat.modules:
  - module: system
    metricsets:
      - cpu
      - load
      - memory
      - network
      - process
      - process_summary
      - uptime
      - socket_summary
      - core
      - diskio
      - filesystem
      - fsstat
    cpu.metrics: [percentages, normalized_percentages, ticks]
    enabled: true
    period: 10s
    processes: [".*"]


processors:
  - add_host_metadata: ~
  - add_fields:
      target: ''
      fields:
        host:
          name: "metricbeat-host"
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

# Output to Elasticsearch (adjust credentials and host as needed)
output.elasticsearch:
  hosts: ["${ELASTICSEARCH_HOSTS}"]
  username: "${ELASTICSEARCH_USERNAME}"
  password: "${ELASTICSEARCH_PASSWORD}"
  protocol: "https"
  ssl.certificate_authorities: ["/usr/share/metricbeat/config/certs/ca/ca.crt"]
  ssl.verification_mode: "full" 

# setup.kibana:
#   host: "${KIBANA_HOST}"

logging.level: debug
logging.selectors: ["*"]
logging.to_files: false
logging.to_stdout: true